packages:
  - 'packages/*'
  - 'infra'

allowBuilds:
  esbuild: true
  protobufjs: true

catalogs:
  core:
    '@types/node': ^24.12.3
    oxfmt: ^0.49.0
    oxlint: ^1.64.0
    typescript: ^6.0.3

autoInstallPeers: true
strictPeerDependencies: false
