name: IaC Deploy

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/iac-deploy.yml
    permissions:
      contents: read
      id-token: write # Required for Pulumi OIDC authentication.
      packages: read # Required by the setup action to install private packages.
    with:
      stack: prod
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
