name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release:
    name: Version or Publish
    uses: ./.github/workflows/release-reusable.yml
    with:
      npm-scope: '@kin0992'
    secrets: inherit
